# Generated by Django 5.0.3 on 2025-02-05 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("linkNo", models.CharField(unique=True)),
                ("linkCode", models.CharField(unique=True)),
                ("linkName", models.CharField(max_length=50)),
                ("linkLengthOfficial", models.FloatField()),
                ("linkLengthActual", models.FloatField()),
                (
                    "kabupaten",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.kabupaten"
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.province"
                    ),
                ),
            ],
            options={
                "db_table": "Link",
            },
        ),
    ]
