# Generated by Django 5.0.3 on 2025-02-12 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roadinventory",
            name="drainTypeL",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="road_inventory_left",
                to="api.draintype",
            ),
        ),
        migrations.AlterField(
            model_name="roadinventory",
            name="drainTypeR",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="road_inventory_right",
                to="api.draintype",
            ),
        ),
        migrations.AlterField(
            model_name="roadinventory",
            name="impassableReason",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="road_inventory",
                to="api.impassible",
            ),
        ),
        migrations.AlterField(
            model_name="roadinventory",
            name="landUseL",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="road_inventory_left",
                to="api.landuse",
            ),
        ),
        migrations.AlterField(
            model_name="roadinventory",
            name="landUseR",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="road_inventory_right",
                to="api.landuse",
            ),
        ),
        migrations.AlterField(
            model_name="roadinventory",
            name="shoulderTypeL",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="road_inventory_left",
                to="api.shouldertype",
            ),
        ),
        migrations.AlterField(
            model_name="roadinventory",
            name="shoulderTypeR",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="road_inventory_right",
                to="api.shouldertype",
            ),
        ),
        migrations.AlterField(
            model_name="roadinventory",
            name="terrain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="road_inventory",
                to="api.terrain",
            ),
        ),
    ]
