# Generated by Django 5.0.3 on 2025-02-05 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kabupaten",
            name="Province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.province",
            ),
        ),
    ]
