# Generated by Django 5.0.3 on 2025-02-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_kabupaten_province"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kabupaten",
            name="id",
        ),
        migrations.RemoveField(
            model_name="province",
            name="id",
        ),
        migrations.AlterField(
            model_name="kabupaten",
            name="KabupatenCode",
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="link",
            name="linkName",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="province",
            name="provinceCode",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
