# Generated by Django 5.0.3 on 2025-02-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_role_role_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="role_name",
            field=models.CharField(
                choices=[
                    ("pfid", "PFID"),
                    ("dpsi", "DPSI"),
                    ("spdjd", "SPDJD"),
                    ("balai", "Balai "),
                    ("provience_lg", "Provincial LG"),
                    ("kabupaten_lg", "Kabupaten LG"),
                ],
                default="pfid",
                max_length=20,
                unique=True,
                verbose_name="Role",
            ),
        ),
    ]
