# Generated by Django 5.0.3 on 2025-02-06 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_kabupaten_id_remove_province_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="balai",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.balai",
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="kabupaten",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.kabupaten",
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.province",
            ),
        ),
    ]
