# Generated by Django 5.0.3 on 2025-02-13 05:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_role_role_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="phoneNumber",
            new_name="phone_number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="contact_person",
        ),
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
    ]
