# Generated by Django 5.1.6 on 2025-02-12 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_role_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadcondition',
            name='depressionsArea',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roadcondition',
            name='drpFrom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='roadcondition',
            name='drpTo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='roadcondition',
            name='edgeDamageArea',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roadcondition',
            name='edgeDamageAreaR',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roadcondition',
            name='erosionArea',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roadcondition',
            name='shoulderCondL',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='roadcondition',
            name='shoulderCondR',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='roadcondition',
            name='drainL',
            field=models.ForeignKey(blank=True, db_column='drainL', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='road_condition_left', to='api.draincondition'),
        ),
        migrations.AlterField(
            model_name='roadcondition',
            name='drainR',
            field=models.ForeignKey(blank=True, db_column='drainR', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='road_condition_right', to='api.draincondition'),
        ),
        migrations.AlterField(
            model_name='roadcondition',
            name='footpathL',
            field=models.ForeignKey(db_column='footpathL', on_delete=django.db.models.deletion.CASCADE, related_name='road_condition_footpath_left', to='api.footpathcondition'),
        ),
        migrations.AlterField(
            model_name='roadcondition',
            name='footpathR',
            field=models.ForeignKey(db_column='footpathR', on_delete=django.db.models.deletion.CASCADE, related_name='road_condition_footpath_right', to='api.footpathcondition'),
        ),
        migrations.AlterField(
            model_name='roadcondition',
            name='linkId',
            field=models.ForeignKey(db_column='linkId', on_delete=django.db.models.deletion.CASCADE, related_name='road_conditions', to='api.link'),
        ),
        migrations.AlterField(
            model_name='roadcondition',
            name='shoulderL',
            field=models.ForeignKey(db_column='shoulderL', on_delete=django.db.models.deletion.CASCADE, related_name='road_condition_shoulder_left', to='api.shouldercondition'),
        ),
        migrations.AlterField(
            model_name='roadcondition',
            name='shoulderR',
            field=models.ForeignKey(db_column='shoulderR', on_delete=django.db.models.deletion.CASCADE, related_name='road_condition_shoulder_right', to='api.shouldercondition'),
        ),
        migrations.AlterField(
            model_name='roadcondition',
            name='slopeL',
            field=models.ForeignKey(db_column='slopeL', on_delete=django.db.models.deletion.CASCADE, related_name='road_condition_slope_left', to='api.slopecondition'),
        ),
        migrations.AlterField(
            model_name='roadcondition',
            name='slopeR',
            field=models.ForeignKey(db_column='slopeR', on_delete=django.db.models.deletion.CASCADE, related_name='road_condition_slope_right', to='api.slopecondition'),
        ),
    ]
