# Generated by Django 5.0.3 on 2025-02-13 07:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_rename_phonenumber_user_phone_number_and_more"),
        ("api", "0005_roadcondition_depressionsarea_roadcondition_drpfrom_and_more"),
    ]

    operations = []
