# Generated by Django 5.0.3 on 2025-02-06 08:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_link_balai_alter_link_kabupaten_alter_link_province"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="link",
            name="balai",
        ),
    ]
