# Generated by Django 5.0.3 on 2025-02-06 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_remove_link_balai"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="balai",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.balai",
            ),
        ),
    ]
