# Generated by Django 5.0.3 on 2025-02-06 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_link_balai"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField()),
                ("codeDescriptionEng", models.CharField(max_length=50)),
                ("codeDescriptionInd", models.CharField(max_length=50)),
                ("order", models.IntegerField()),
            ],
            options={
                "db_table": "LinkClassCode",
            },
        ),
        migrations.CreateModel(
            name="LinkFunction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField()),
                ("codeDescriptionEng", models.CharField(max_length=50)),
                ("codeDescriptionInd", models.CharField(max_length=50)),
                ("order", models.IntegerField()),
            ],
            options={
                "db_table": "LinkFunctionCode",
            },
        ),
        migrations.CreateModel(
            name="LinkStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField()),
                ("codeDescriptionEng", models.CharField(max_length=50)),
                ("codeDescriptionInd", models.CharField(max_length=50)),
                ("order", models.IntegerField()),
            ],
            options={
                "db_table": "LinkStatusCode",
            },
        ),
        migrations.RemoveField(
            model_name="link",
            name="balai",
        ),
        migrations.RemoveField(
            model_name="link",
            name="id",
        ),
        migrations.AddField(
            model_name="link",
            name="aadt",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="link",
            name="accessStatus",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="link",
            name="cumesa",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="link",
            name="esa0",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="link",
            name="inbound",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="link",
            name="linkId",
            field=models.CharField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="link",
            name="mca2",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="link",
            name="mca3",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="link",
            name="mca4",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="link",
            name="mca5",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="link",
            name="projectNumber",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="link",
            name="wti",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="link",
            name="linkLengthActual",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="link",
            name="linkLengthOfficial",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="link",
            name="linkName",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="link",
            name="class_field",
            field=models.ForeignKey(
                blank=True,
                db_column="class",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.linkclass",
            ),
        ),
        migrations.AddField(
            model_name="link",
            name="function",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.linkfunction",
            ),
        ),
        migrations.AddField(
            model_name="link",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.linkstatus",
            ),
        ),
    ]
