# Generated by Django 5.0.3 on 2025-02-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_linkclass_linkfunction_linkstatus_remove_link_balai_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="linkId",
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
