# Generated by Django 5.0.3 on 2025-02-07 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_user_contact_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phoneNumber",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in Indonesian format, starting with +62 followed by 9 to 13 digits.",
                        regex="^\\+62\\d{9,13}$",
                    )
                ],
            ),
        ),
    ]
