# Generated by Django 5.0.3 on 2025-02-10 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_draincondition_footpathcondition_shouldercondition_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrainType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField()),
                ("codeDescriptionEng", models.CharField(max_length=50)),
                ("codeDescriptionInd", models.CharField(max_length=50)),
                ("order", models.IntegerField()),
            ],
            options={
                "db_table": "DrainType",
            },
        ),
        migrations.CreateModel(
            name="Impassible",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField()),
                ("codeDescriptionEng", models.CharField(max_length=50)),
                ("codeDescriptionInd", models.CharField(max_length=50)),
                ("order", models.IntegerField()),
            ],
            options={
                "db_table": "Impassible",
            },
        ),
        migrations.CreateModel(
            name="LandUse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField()),
                ("codeDescriptionEng", models.CharField(max_length=50)),
                ("codeDescriptionInd", models.CharField(max_length=50)),
                ("order", models.IntegerField()),
            ],
            options={
                "db_table": "LandUse",
            },
        ),
        migrations.CreateModel(
            name="ShoulderType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField()),
                ("codeDescriptionEng", models.CharField(max_length=50)),
                ("codeDescriptionInd", models.CharField(max_length=50)),
                ("order", models.IntegerField()),
            ],
            options={
                "db_table": "ShouderType",
            },
        ),
        migrations.CreateModel(
            name="Terrain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField()),
                ("codeDescriptionEng", models.CharField(max_length=50)),
                ("codeDescriptionInd", models.CharField(max_length=50)),
                ("order", models.IntegerField()),
            ],
            options={
                "db_table": "Terrain",
            },
        ),
        migrations.CreateModel(
            name="RoadInventory",
            fields=[
                (
                    "roadInventoryId",
                    models.CharField(primary_key=True, serialize=False),
                ),
                ("linkNo", models.BigIntegerField(blank=True, null=True)),
                ("chainageFrom", models.IntegerField(blank=True, null=True)),
                ("chainageTo", models.IntegerField(blank=True, null=True)),
                ("drpFrom", models.IntegerField(blank=True, null=True)),
                ("offsetFrom", models.IntegerField(blank=True, null=True)),
                ("drpTo", models.IntegerField(blank=True, null=True)),
                ("offsetTo", models.IntegerField(blank=True, null=True)),
                ("paveWidth", models.FloatField(blank=True, null=True)),
                ("row", models.IntegerField(blank=True, null=True)),
                ("paveType", models.IntegerField(blank=True, null=True)),
                ("shoulderWidthL", models.FloatField(blank=True, null=True)),
                ("shoulderWidthR", models.FloatField(blank=True, null=True)),
                ("impassable", models.BooleanField()),
                (
                    "drainTypeL",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="road_inventory_left",
                        to="api.draintype",
                    ),
                ),
                (
                    "drainTypeR",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="road_inventory_right",
                        to="api.draintype",
                    ),
                ),
                (
                    "impassableReason",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="road_inventory",
                        to="api.impassible",
                    ),
                ),
                (
                    "landUseL",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="road_inventory_left",
                        to="api.landuse",
                    ),
                ),
                (
                    "landUseR",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="road_inventory_right",
                        to="api.landuse",
                    ),
                ),
                (
                    "linkId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="road_inventory",
                        to="api.link",
                    ),
                ),
                (
                    "shoulderTypeL",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="road_inventory_left",
                        to="api.shouldertype",
                    ),
                ),
                (
                    "shoulderTypeR",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="road_inventory_right",
                        to="api.shouldertype",
                    ),
                ),
                (
                    "terrain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="road_inventory",
                        to="api.terrain",
                    ),
                ),
            ],
            options={
                "db_table": "RoadInventory",
            },
        ),
    ]
