# Generated by Django 5.0.3 on 2025-02-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_draintype_impassible_landuse_shouldertype_terrain_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="role_name",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Admin"),
                    ("pfid", "PFID"),
                    ("dpsi", "DPSI"),
                    ("spdjd", "SPDJD"),
                    ("balai_lg", "Balai LG"),
                    ("provience_lg", "Provincial LG"),
                    ("kabupaten_lg", "Kabupaten LG"),
                ],
                default="pfid",
                max_length=20,
                unique=True,
                verbose_name="Role",
            ),
        ),
    ]
