# Generated by Django 5.0.3 on 2025-01-16 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_approvalrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unitcost_periodic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_status",
                    models.CharField(
                        choices=[
                            ("provincial", "Provincial"),
                            ("kabupaten", "Kabupaten"),
                        ],
                        default=True,
                        max_length=20,
                        verbose_name="Link Status",
                    ),
                ),
                ("drp_from", models.IntegerField()),
                ("drp_to", models.IntegerField()),
                (
                    "periodic_maintenance_unitcost",
                    models.DecimalField(decimal_places=5, max_digits=10),
                ),
                (
                    "kabupaten",
                    models.ForeignKey(
                        default=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.kabupaten",
                        verbose_name="Kabupaten",
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        default=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.province",
                        verbose_name="Province",
                    ),
                ),
            ],
        ),
    ]
