# Generated by Django 5.0.3 on 2025-01-21 08:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_unitcost_periodic"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Unitcost_periodic",
        ),
    ]
