# Generated by Django 5.0.3 on 2025-01-27 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_delete_unitcost_periodic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roadinventory",
            name="impassable_reason",
        ),
        migrations.RemoveField(
            model_name="roadinventory",
            name="pavement_subtype_width",
        ),
        migrations.RemoveField(
            model_name="roadinventory",
            name="row_subtype_width",
        ),
        migrations.RemoveField(
            model_name="roadinventory",
            name="shoulder_L_subtype_width",
        ),
        migrations.RemoveField(
            model_name="roadinventory",
            name="shoulder_R_subtype_width",
        ),
        migrations.AddField(
            model_name="roadinventory",
            name="pavement_width",
            field=models.FloatField(default=1, verbose_name="Pavement Width (m)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="roadinventory",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("jembatan_runtuh", "Jembatan Runtuh"),
                    ("sungai_tanpa_jembatan", "Sungai Tanpa Jembatan"),
                    ("tak_dapat_dilalui_musim", "Tak Dapat Dilalui Selama Musim"),
                    ("lainnya", "Lainnya"),
                ],
                max_length=30,
                null=True,
                verbose_name="Reason",
            ),
        ),
        migrations.AddField(
            model_name="roadinventory",
            name="row_width",
            field=models.FloatField(default=1, verbose_name="ROW Width (m)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="roadinventory",
            name="shoulder_L_width",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Shoulder Left Width (m)"
            ),
        ),
        migrations.AddField(
            model_name="roadinventory",
            name="shoulder_R_width",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Shoulder Right Width (m)"
            ),
        ),
        migrations.AlterField(
            model_name="roadinventory",
            name="chainage_from",
            field=models.FloatField(verbose_name="Chainage From (km)"),
        ),
        migrations.AlterField(
            model_name="roadinventory",
            name="chainage_to",
            field=models.FloatField(verbose_name="Chainage To (km)"),
        ),
        migrations.AlterField(
            model_name="roadinventory",
            name="drain_type_left",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tak_ada", "Tak Ada"),
                    ("tak_perlu", "Tak Perlu"),
                    ("tanah", "Tanah"),
                    ("pasangan_batu_terbuka", "Pasangan Batu Terbuka"),
                    ("pasangan_batu_tertutup", "Pasangan Batu Tertutup"),
                ],
                max_length=30,
                null=True,
                verbose_name="Drain Type Left",
            ),
        ),
        migrations.AlterField(
            model_name="roadinventory",
            name="drain_type_right",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tak_ada", "Tak Ada"),
                    ("tak_perlu", "Tak Perlu"),
                    ("tanah", "Tanah"),
                    ("pasangan_batu_terbuka", "Pasangan Batu Terbuka"),
                    ("pasangan_batu_tertutup", "Pasangan Batu Tertutup"),
                ],
                max_length=30,
                null=True,
                verbose_name="Drain Type Right",
            ),
        ),
        migrations.AlterField(
            model_name="roadinventory",
            name="kabupaten",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.kabupaten",
                verbose_name="Kabupaten",
            ),
        ),
        migrations.AlterField(
            model_name="roadinventory",
            name="land_use_left",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tak_ada", "Tak Ada"),
                    ("agrikultur", "Agrikultur"),
                    ("desa", "Desa"),
                    ("kota", "Kota"),
                    ("hutan", "Hutan"),
                ],
                max_length=20,
                null=True,
                verbose_name="Land Use Left",
            ),
        ),
        migrations.AlterField(
            model_name="roadinventory",
            name="land_use_right",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tak_ada", "Tak Ada"),
                    ("agrikultur", "Agrikultur"),
                    ("desa", "Desa"),
                    ("kota", "Kota"),
                    ("hutan", "Hutan"),
                ],
                max_length=20,
                null=True,
                verbose_name="Land Use Right",
            ),
        ),
        migrations.AlterField(
            model_name="roadinventory",
            name="link",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.link",
                verbose_name="Link",
            ),
        ),
        migrations.AlterField(
            model_name="roadinventory",
            name="link_status",
            field=models.CharField(
                choices=[("provincial", "Provincial"), ("kabupaten", "Kabupaten")],
                default="provincial",
                max_length=20,
                verbose_name="Link Status",
            ),
        ),
        migrations.AlterField(
            model_name="roadinventory",
            name="pavement_type",
            field=models.CharField(
                choices=[
                    ("beton", "Beton"),
                    ("blok_beton", "Blok Beton"),
                    ("aspal", "Aspal"),
                    ("lapen", "Lapen"),
                    ("batu_kali", "Batu Kali"),
                    ("kerikil", "Kerikil"),
                    ("tanah", "Tanah"),
                ],
                max_length=20,
                verbose_name="Pavement Type",
            ),
        ),
        migrations.AlterField(
            model_name="roadinventory",
            name="province",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.province",
                verbose_name="Province",
            ),
        ),
        migrations.AlterField(
            model_name="roadinventory",
            name="shoulder_L_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beton", "Beton"),
                    ("blok_beton", "Blok Beton"),
                    ("aspal", "Aspal"),
                    ("lapen", "Lapen"),
                    ("batu_kali", "Batu Kali"),
                    ("kerikil", "Kerikil"),
                    ("tanah", "Tanah"),
                ],
                max_length=20,
                null=True,
                verbose_name="Shoulder Left Type",
            ),
        ),
        migrations.AlterField(
            model_name="roadinventory",
            name="shoulder_R_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beton", "Beton"),
                    ("blok_beton", "Blok Beton"),
                    ("aspal", "Aspal"),
                    ("lapen", "Lapen"),
                    ("batu_kali", "Batu Kali"),
                    ("kerikil", "Kerikil"),
                    ("tanah", "Tanah"),
                ],
                max_length=20,
                null=True,
                verbose_name="Shoulder Right Type",
            ),
        ),
        migrations.AlterField(
            model_name="roadinventory",
            name="terrain",
            field=models.CharField(
                choices=[("datar", "Datar"), ("bukit", "Bukit"), ("gunung", "Gunung")],
                max_length=20,
                verbose_name="Terrain",
            ),
        ),
    ]
